package SmartFarming.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class Farmer_Constraints extends BaseConstraintsDescriptor {
  public Farmer_Constraints() {
    super(CONCEPTS.Farmer$1W);
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Farmer$1W = MetaAdapterFactory.getConcept(0x5284d1bee3634c06L, 0xa2364161e9028c0dL, 0x346b31548e5bd36cL, "SmartFarming.structure.Farmer");
  }
}
