/*
 * generated by Xtext 2.25.0
 */
package com.se4gd.smartfarming.ide;


/**
 * Use this class to register ide components.
 */
public class SmartFarmingIdeModule extends AbstractSmartFarmingIdeModule {
}
