/*
 * generated by Xtext 2.25.0
 */
package com.se4gd.smartfarming.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import com.se4gd.smartfarming.SmartFarmingRuntimeModule;
import com.se4gd.smartfarming.SmartFarmingStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class SmartFarmingIdeSetup extends SmartFarmingStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new SmartFarmingRuntimeModule(), new SmartFarmingIdeModule()));
	}
	
}
