/*
 * generated by Xtext 2.25.0
 */
package com.se4gd.smartfarming;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class SmartFarmingStandaloneSetup extends SmartFarmingStandaloneSetupGenerated {

	public static void doSetup() {
		new SmartFarmingStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
