/*
 * generated by Xtext 2.25.0
 */
package com.se4gd.smartfarming.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSmartFarmingScopeProvider extends DelegatingScopeProvider {
}
