package SmartFarming.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_ControlActions extends EnumerationDescriptorBase {

  public EnumerationDescriptor_ControlActions() {
    super(0x5284d1bee3634c06L, 0xa2364161e9028c0dL, 0x6813e10dbb96261bL, "ControlActions", "r:17f8e5c2-54e9-4f66-903e-aba76cf0e1c5(SmartFarming.structure)/7499585253600011803");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_Increase_0 = new EnumerationDescriptor.MemberDescriptor("Increase", "Increase", 0x6813e10dbb96261cL, "r:17f8e5c2-54e9-4f66-903e-aba76cf0e1c5(SmartFarming.structure)/7499585253600011804");
  private final EnumerationDescriptor.MemberDescriptor myMember_Decrease_0 = new EnumerationDescriptor.MemberDescriptor("Decrease", "Decrease", 0x6813e10dbb96261dL, "r:17f8e5c2-54e9-4f66-903e-aba76cf0e1c5(SmartFarming.structure)/7499585253600011805");
  private final EnumerationDescriptor.MemberDescriptor myMember_ON_0 = new EnumerationDescriptor.MemberDescriptor("ON", "ON", 0x6813e10dbb962620L, "r:17f8e5c2-54e9-4f66-903e-aba76cf0e1c5(SmartFarming.structure)/7499585253600011808");
  private final EnumerationDescriptor.MemberDescriptor myMember_OFF_0 = new EnumerationDescriptor.MemberDescriptor("OFF", "OFF", 0x6813e10dbb962624L, "r:17f8e5c2-54e9-4f66-903e-aba76cf0e1c5(SmartFarming.structure)/7499585253600011812");
  private final EnumerationDescriptor.MemberDescriptor myMember_Alert_0 = new EnumerationDescriptor.MemberDescriptor("Alert", "Alert", 0x6813e10dbb962629L, "r:17f8e5c2-54e9-4f66-903e-aba76cf0e1c5(SmartFarming.structure)/7499585253600011817");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x5284d1bee3634c06L, 0xa2364161e9028c0dL, 0x6813e10dbb96261bL, 0x6813e10dbb96261cL, 0x6813e10dbb96261dL, 0x6813e10dbb962620L, 0x6813e10dbb962624L, 0x6813e10dbb962629L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_Increase_0, myMember_Decrease_0, myMember_ON_0, myMember_OFF_0, myMember_Alert_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "Increase":
        return myMember_Increase_0;
      case "Decrease":
        return myMember_Decrease_0;
      case "ON":
        return myMember_ON_0;
      case "OFF":
        return myMember_OFF_0;
      case "Alert":
        return myMember_Alert_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
