package SmartFarming.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_SensorState extends EnumerationDescriptorBase {

  public EnumerationDescriptor_SensorState() {
    super(0x5284d1bee3634c06L, 0xa2364161e9028c0dL, 0x4cd0d7ded305019dL, "SensorState", "r:17f8e5c2-54e9-4f66-903e-aba76cf0e1c5(SmartFarming.structure)/5535161294061371805");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_Active_0 = new EnumerationDescriptor.MemberDescriptor("Active", "Active", 0x4cd0d7ded305019eL, "r:17f8e5c2-54e9-4f66-903e-aba76cf0e1c5(SmartFarming.structure)/5535161294061371806");
  private final EnumerationDescriptor.MemberDescriptor myMember_Passive_0 = new EnumerationDescriptor.MemberDescriptor("Passive", "Passive", 0x4cd0d7ded30528abL, "r:17f8e5c2-54e9-4f66-903e-aba76cf0e1c5(SmartFarming.structure)/5535161294061381803");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x5284d1bee3634c06L, 0xa2364161e9028c0dL, 0x4cd0d7ded305019dL, 0x4cd0d7ded305019eL, 0x4cd0d7ded30528abL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_Active_0, myMember_Passive_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "Active":
        return myMember_Active_0;
      case "Passive":
        return myMember_Passive_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
