package SmartFarming.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_ControlType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_ControlType() {
    super(0x5284d1bee3634c06L, 0xa2364161e9028c0dL, 0x6813e10dbb962604L, "ControlType", "r:17f8e5c2-54e9-4f66-903e-aba76cf0e1c5(SmartFarming.structure)/7499585253600011780");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_AirConditioner_0 = new EnumerationDescriptor.MemberDescriptor("AirConditioner", "AirConditioner", 0x6813e10dbb962605L, "r:17f8e5c2-54e9-4f66-903e-aba76cf0e1c5(SmartFarming.structure)/7499585253600011781");
  private final EnumerationDescriptor.MemberDescriptor myMember_Nutrient_0 = new EnumerationDescriptor.MemberDescriptor("Nutrient", "Nutrient", 0x6813e10dbb962606L, "r:17f8e5c2-54e9-4f66-903e-aba76cf0e1c5(SmartFarming.structure)/7499585253600011782");
  private final EnumerationDescriptor.MemberDescriptor myMember_Light_0 = new EnumerationDescriptor.MemberDescriptor("Light", "Light", 0x6813e10dbb962609L, "r:17f8e5c2-54e9-4f66-903e-aba76cf0e1c5(SmartFarming.structure)/7499585253600011785");
  private final EnumerationDescriptor.MemberDescriptor myMember_Oxygen_0 = new EnumerationDescriptor.MemberDescriptor("Oxygen", "Oxygen", 0x6813e10dbb96260dL, "r:17f8e5c2-54e9-4f66-903e-aba76cf0e1c5(SmartFarming.structure)/7499585253600011789");
  private final EnumerationDescriptor.MemberDescriptor myMember_CO2_0 = new EnumerationDescriptor.MemberDescriptor("CO2", "CO2", 0x6813e10dbb962612L, "r:17f8e5c2-54e9-4f66-903e-aba76cf0e1c5(SmartFarming.structure)/7499585253600011794");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x5284d1bee3634c06L, 0xa2364161e9028c0dL, 0x6813e10dbb962604L, 0x6813e10dbb962605L, 0x6813e10dbb962606L, 0x6813e10dbb962609L, 0x6813e10dbb96260dL, 0x6813e10dbb962612L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_AirConditioner_0, myMember_Nutrient_0, myMember_Light_0, myMember_Oxygen_0, myMember_CO2_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "AirConditioner":
        return myMember_AirConditioner_0;
      case "Nutrient":
        return myMember_Nutrient_0;
      case "Light":
        return myMember_Light_0;
      case "Oxygen":
        return myMember_Oxygen_0;
      case "CO2":
        return myMember_CO2_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
