package SmartFarming.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_CropGroup extends EnumerationDescriptorBase {

  public EnumerationDescriptor_CropGroup() {
    super(0x5284d1bee3634c06L, 0xa2364161e9028c0dL, 0x346b31548e5bd389L, "CropGroup", "r:17f8e5c2-54e9-4f66-903e-aba76cf0e1c5(SmartFarming.structure)/3777166951715689353");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_Vegetable_0 = new EnumerationDescriptor.MemberDescriptor("Vegetable", "Vegetable", 0x346b31548e5bd38aL, "r:17f8e5c2-54e9-4f66-903e-aba76cf0e1c5(SmartFarming.structure)/3777166951715689354");
  private final EnumerationDescriptor.MemberDescriptor myMember_Fruit_0 = new EnumerationDescriptor.MemberDescriptor("Fruit", "Fruit", 0x346b31548e5bd38bL, "r:17f8e5c2-54e9-4f66-903e-aba76cf0e1c5(SmartFarming.structure)/3777166951715689355");
  private final EnumerationDescriptor.MemberDescriptor myMember_Flower_0 = new EnumerationDescriptor.MemberDescriptor("Flower", "Flower", 0x346b31548e5bd38eL, "r:17f8e5c2-54e9-4f66-903e-aba76cf0e1c5(SmartFarming.structure)/3777166951715689358");
  private final EnumerationDescriptor.MemberDescriptor myMember_Tuber_0 = new EnumerationDescriptor.MemberDescriptor("Tuber", "Tuber", 0x346b31548e5bd392L, "r:17f8e5c2-54e9-4f66-903e-aba76cf0e1c5(SmartFarming.structure)/3777166951715689362");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x5284d1bee3634c06L, 0xa2364161e9028c0dL, 0x346b31548e5bd389L, 0x346b31548e5bd38aL, 0x346b31548e5bd38bL, 0x346b31548e5bd38eL, 0x346b31548e5bd392L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_Vegetable_0, myMember_Fruit_0, myMember_Flower_0, myMember_Tuber_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "Vegetable":
        return myMember_Vegetable_0;
      case "Fruit":
        return myMember_Fruit_0;
      case "Flower":
        return myMember_Flower_0;
      case "Tuber":
        return myMember_Tuber_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
