package SmartFarming.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_CommunicationType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_CommunicationType() {
    super(0x5284d1bee3634c06L, 0xa2364161e9028c0dL, 0x75c7c5f96ef4bb06L, "CommunicationType", "r:17f8e5c2-54e9-4f66-903e-aba76cf0e1c5(SmartFarming.structure)/8486969697902050054");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_ZigBee_0 = new EnumerationDescriptor.MemberDescriptor("ZigBee", "ZigBee", 0x75c7c5f96ef4bb07L, "r:17f8e5c2-54e9-4f66-903e-aba76cf0e1c5(SmartFarming.structure)/8486969697902050055");
  private final EnumerationDescriptor.MemberDescriptor myMember_MQTT_0 = new EnumerationDescriptor.MemberDescriptor("MQTT", "MQTT", 0x75c7c5f96ef4bb08L, "r:17f8e5c2-54e9-4f66-903e-aba76cf0e1c5(SmartFarming.structure)/8486969697902050056");
  private final EnumerationDescriptor.MemberDescriptor myMember_CoAP_0 = new EnumerationDescriptor.MemberDescriptor("CoAP", "CoAP", 0x75c7c5f96ef4bb0bL, "r:17f8e5c2-54e9-4f66-903e-aba76cf0e1c5(SmartFarming.structure)/8486969697902050059");
  private final EnumerationDescriptor.MemberDescriptor myMember_HTTP_0 = new EnumerationDescriptor.MemberDescriptor("HTTP", "HTTP", 0x75c7c5f96ef4bb0fL, "r:17f8e5c2-54e9-4f66-903e-aba76cf0e1c5(SmartFarming.structure)/8486969697902050063");
  private final EnumerationDescriptor.MemberDescriptor myMember_WiFi_0 = new EnumerationDescriptor.MemberDescriptor("WiFi", "WiFi", 0x75c7c5f96ef4bb14L, "r:17f8e5c2-54e9-4f66-903e-aba76cf0e1c5(SmartFarming.structure)/8486969697902050068");
  private final EnumerationDescriptor.MemberDescriptor myMember_Bluetooth_0 = new EnumerationDescriptor.MemberDescriptor("Bluetooth", "Bluetooth", 0x75c7c5f96ef4bb1aL, "r:17f8e5c2-54e9-4f66-903e-aba76cf0e1c5(SmartFarming.structure)/8486969697902050074");
  private final EnumerationDescriptor.MemberDescriptor myMember_ZWave_0 = new EnumerationDescriptor.MemberDescriptor("ZWave", "ZWave", 0x75c7c5f96ef4bb21L, "r:17f8e5c2-54e9-4f66-903e-aba76cf0e1c5(SmartFarming.structure)/8486969697902050081");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x5284d1bee3634c06L, 0xa2364161e9028c0dL, 0x75c7c5f96ef4bb06L, 0x75c7c5f96ef4bb07L, 0x75c7c5f96ef4bb08L, 0x75c7c5f96ef4bb0bL, 0x75c7c5f96ef4bb0fL, 0x75c7c5f96ef4bb14L, 0x75c7c5f96ef4bb1aL, 0x75c7c5f96ef4bb21L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_ZigBee_0, myMember_MQTT_0, myMember_CoAP_0, myMember_HTTP_0, myMember_WiFi_0, myMember_Bluetooth_0, myMember_ZWave_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "ZigBee":
        return myMember_ZigBee_0;
      case "MQTT":
        return myMember_MQTT_0;
      case "CoAP":
        return myMember_CoAP_0;
      case "HTTP":
        return myMember_HTTP_0;
      case "WiFi":
        return myMember_WiFi_0;
      case "Bluetooth":
        return myMember_Bluetooth_0;
      case "ZWave":
        return myMember_ZWave_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
