package SmartFarming.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_OutputType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_OutputType() {
    super(0x5284d1bee3634c06L, 0xa2364161e9028c0dL, 0x6813e10dbb9625f2L, "OutputType", "r:17f8e5c2-54e9-4f66-903e-aba76cf0e1c5(SmartFarming.structure)/7499585253600011762");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_LineGraph_0 = new EnumerationDescriptor.MemberDescriptor("LineGraph", "LineGraph", 0x6813e10dbb9625f3L, "r:17f8e5c2-54e9-4f66-903e-aba76cf0e1c5(SmartFarming.structure)/7499585253600011763");
  private final EnumerationDescriptor.MemberDescriptor myMember_PieChart_0 = new EnumerationDescriptor.MemberDescriptor("PieChart", "PieChart", 0x6813e10dbb9625f4L, "r:17f8e5c2-54e9-4f66-903e-aba76cf0e1c5(SmartFarming.structure)/7499585253600011764");
  private final EnumerationDescriptor.MemberDescriptor myMember_BarChart_0 = new EnumerationDescriptor.MemberDescriptor("BarChart", "BarChart", 0x6813e10dbb9625f7L, "r:17f8e5c2-54e9-4f66-903e-aba76cf0e1c5(SmartFarming.structure)/7499585253600011767");
  private final EnumerationDescriptor.MemberDescriptor myMember_Tabular_0 = new EnumerationDescriptor.MemberDescriptor("Tabular", "Tabular", 0x6813e10dbb9625fbL, "r:17f8e5c2-54e9-4f66-903e-aba76cf0e1c5(SmartFarming.structure)/7499585253600011771");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x5284d1bee3634c06L, 0xa2364161e9028c0dL, 0x6813e10dbb9625f2L, 0x6813e10dbb9625f3L, 0x6813e10dbb9625f4L, 0x6813e10dbb9625f7L, 0x6813e10dbb9625fbL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_LineGraph_0, myMember_PieChart_0, myMember_BarChart_0, myMember_Tabular_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "LineGraph":
        return myMember_LineGraph_0;
      case "PieChart":
        return myMember_PieChart_0;
      case "BarChart":
        return myMember_BarChart_0;
      case "Tabular":
        return myMember_Tabular_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
