package SmartFarming.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Analytics = 0;
  public static final int CommunicationProtocol = 1;
  public static final int ControlSystem = 2;
  public static final int Crop = 3;
  public static final int Farm = 4;
  public static final int Farmer = 5;
  public static final int Gateway = 6;
  public static final int IoTSystem = 7;
  public static final int MonitoringSystem = 8;
  public static final int Service = 9;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x5284d1bee3634c06L, 0xa2364161e9028c0dL);
    builder.put(0x6813e10dbb9625dfL, Analytics);
    builder.put(0x75c7c5f96ef4bb03L, CommunicationProtocol);
    builder.put(0x6813e10dbb962600L, ControlSystem);
    builder.put(0x346b31548e5bd384L, Crop);
    builder.put(0xad19f946497d8c4L, Farm);
    builder.put(0x346b31548e5bd36cL, Farmer);
    builder.put(0x75c7c5f96ef4bafbL, Gateway);
    builder.put(0x346b31548e5bd3a1L, IoTSystem);
    builder.put(0x6813e10dbb96262fL, MonitoringSystem);
    builder.put(0x6813e10dbb9625c4L, Service);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
