/*
 * generated by Xtext 2.25.0
 */
package com.se4gd.smartfarming.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class SmartFarmingUiModule extends AbstractSmartFarmingUiModule {

	public SmartFarmingUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
