/*
 * generated by Xtext 2.25.0
 */
package com.se4gd.smartfarming.ui.tests;

import com.google.inject.Injector;
import com.se4gd.smartfarming.ui.internal.SmartfarmingActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class SmartFarmingUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return SmartfarmingActivator.getInstance().getInjector("com.se4gd.smartfarming.SmartFarming");
	}

}
