/*
 * generated by Xtext 2.25.0
 */
package com.se4gd.smartfarming.parser.antlr;

import com.google.inject.Inject;
import com.se4gd.smartfarming.parser.antlr.internal.InternalSmartFarmingParser;
import com.se4gd.smartfarming.services.SmartFarmingGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class SmartFarmingParser extends AbstractAntlrParser {

	@Inject
	private SmartFarmingGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSmartFarmingParser createParser(XtextTokenStream stream) {
		return new InternalSmartFarmingParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Farm";
	}

	public SmartFarmingGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SmartFarmingGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
