/*
 * generated by Xtext 2.25.0
 */
package com.se4gd.smartfarming.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SmartFarmingAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("com/se4gd/smartfarming/parser/antlr/internal/InternalSmartFarming.tokens");
	}
}
